In [1]:
import numpy as np
import cv2
import openpose as op

In [5]:
img = cv2.imread('pose/test.jpg')#读图
im = cv2.resize(img,(360,640))
dst_im = cv2.flip(im, -1)  #原型：cv2.flip(src, flipCode[, dst]) → dst  flipCode表示对称轴 0：x轴  1：y轴.  -1：both
dst_im = cv2.transpose(dst_im)
cv2.imshow("test",im )
cv2.imshow("test1",dst_im )
#  add below code
cv2.waitKey(0)
cv2.destroyAllWindows()

In [4]:
keyary

array([[[176.40828   , 151.98447   ,   0.87286294],
        [176.32414   , 205.9922    ,   0.90052503],
        [129.32419   , 207.72658   ,   0.8048624 ],
        [ 61.447285  , 214.65536   ,   0.8633173 ],
        [ 37.124958  , 157.2431    ,   0.7907722 ],
        [225.11444   , 204.20352   ,   0.84200335],
        [287.83688   , 232.03578   ,   0.847268  ],
        [322.6059    , 284.2719    ,   0.8474652 ],
        [183.31525   , 352.16986   ,   0.7213101 ],
        [153.76129   , 352.22345   ,   0.7026322 ],
        [148.48889   , 440.9738    ,   0.83793473],
        [143.25247   , 521.13055   ,   0.9026099 ],
        [212.9425    , 350.4312    ,   0.7151834 ],
        [226.87077   , 442.7759    ,   0.7829107 ],
        [237.32664   , 526.3376    ,   0.81665635],
        [167.62979   , 144.9524    ,   0.931825  ],
        [186.82173   , 143.28882   ,   0.92752236],
        [150.26547   , 152.02057   ,   0.89900756],
        [200.70433   , 151.96594   ,   0.83378214],
        [258

In [3]:
keypage,keyary = op.getkey(img)


In [6]:
ary1 = keyary[:,:,:2].copy()


In [13]:
ary1 = np.vstack((ary1,keyary[:,:,:2]))

In [15]:
ary1

array([[[176.40828 , 151.98447 ],
        [176.32414 , 205.9922  ],
        [129.32419 , 207.72658 ],
        [ 61.447285, 214.65536 ],
        [ 37.124958, 157.2431  ],
        [225.11444 , 204.20352 ],
        [287.83688 , 232.03578 ],
        [322.6059  , 284.2719  ],
        [183.31525 , 352.16986 ],
        [153.76129 , 352.22345 ],
        [148.48889 , 440.9738  ],
        [143.25247 , 521.13055 ],
        [212.9425  , 350.4312  ],
        [226.87077 , 442.7759  ],
        [237.32664 , 526.3376  ],
        [167.62979 , 144.9524  ],
        [186.82173 , 143.28882 ],
        [150.26547 , 152.02057 ],
        [200.70433 , 151.96594 ],
        [258.17255 , 561.1176  ],
        [265.1766  , 552.4723  ],
        [230.33891 , 535.03094 ],
        [111.94971 , 547.24524 ],
        [110.14739 , 540.253   ],
        [148.47018 , 529.83716 ]],

       [[176.40828 , 151.98447 ],
        [176.32414 , 205.9922  ],
        [129.32419 , 207.72658 ],
        [ 61.447285, 214.65536 ],
        [ 37

In [12]:
keyary.shape

(1, 25, 3)

In [21]:
np.save('pose/test.npy',ary1)

In [22]:
ary2 = np.load('pose/test.npy')

In [24]:
ary2

array([[[176.40828 , 151.98447 ],
        [176.32414 , 205.9922  ],
        [129.32419 , 207.72658 ],
        [ 61.447285, 214.65536 ],
        [ 37.124958, 157.2431  ],
        [225.11444 , 204.20352 ],
        [287.83688 , 232.03578 ],
        [322.6059  , 284.2719  ],
        [183.31525 , 352.16986 ],
        [153.76129 , 352.22345 ],
        [148.48889 , 440.9738  ],
        [143.25247 , 521.13055 ],
        [212.9425  , 350.4312  ],
        [226.87077 , 442.7759  ],
        [237.32664 , 526.3376  ],
        [167.62979 , 144.9524  ],
        [186.82173 , 143.28882 ],
        [150.26547 , 152.02057 ],
        [200.70433 , 151.96594 ],
        [258.17255 , 561.1176  ],
        [265.1766  , 552.4723  ],
        [230.33891 , 535.03094 ],
        [111.94971 , 547.24524 ],
        [110.14739 , 540.253   ],
        [148.47018 , 529.83716 ]],

       [[176.40828 , 151.98447 ],
        [176.32414 , 205.9922  ],
        [129.32419 , 207.72658 ],
        [ 61.447285, 214.65536 ],
        [ 37

In [48]:
img = np.zeros((512, 512, 3), np.uint8)
i = 1
font = cv2.FONT_HERSHEY_SIMPLEX
cv2.putText(img,str(i),(10,500),font,0.3,(255,255,255),1)
cv2.imshow("test", img)
#  add below code
cv2.waitKey(0)
cv2.destroyAllWindows()